CREATE PROCEDURE SP_ADD_PRODUCT @PRODUCTNAME NVARCHAR(100), @PRICE DECIMAL, @QUANTITY INT 

AS

INSERT INTO PRODUCTS (ProductName, Price, Quantity)
OUTPUT INSERTED.*
VALUES (@PRODUCTNAME, @PRICE, @QUANTITY)

GO