CREATE PROCEDURE SP_UPDATE_PRODUCT @PRODUCT_ID INT, @PRODUCT_NAME NVARCHAR(100), @PRICE DECIMAL, @QUANTITY INT

AS

UPDATE	PRODUCTS 
SET		PRODUCTNAME = @PRODUCT_NAME,
		PRICE = @PRICE,
		Quantity = @QUANTITY
WHERE	ProductId = @PRODUCT_ID